# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    parallelism: 3 
    working_directory: ~/repos 
    environment:
      BUNDLE_PATH: vendor/bundle
    docker:
      - image: circleci/ruby:2.4-node
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: ${BUNDLE_PATH}
    branches:
      ignore:
        - gh-pages
    steps: # a collection of executable commands

      - checkout # special step to check out source code to working directory

      # Show environment
      - run:
          name: "Show version"
          command: |
            ruby --version 
            bundle --version
            node --version
            npm --version

      # Make sure all dependencies in your Gemfile are available. 
      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
            - gems-
      - run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - ${BUNDLE_PATH}

      # Make sure all dependencies in your package.json are available. 
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
            - node_modules-
      - run: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Run tests
      - run: npm test

      # Run lints
      - run: npm run lint

      # Build a site
      - run: 
          command: bundle exec middleman build
          when: on_success

      # Deploy a site
      # - deploy:
      #     name: start master deploy
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #           git config --global user.email msn088g@gmail.com 
      #           git config --global user.name circleci
      #           git fetch origin gh-pages
      #           bundle exec middleman deploy
      #       fi

      # # Add SSH keys from a project’s settings to a container
      # - add_ssh_keys


      - store_test_results:
          path: test-results



    # workflows:
    #   version: 2
